version: "3.4"

# Services definition for local building & deployment

services:

  app:
    # Build
    image: ${IMAGES_PREFIX:-app}-app
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
      target: app_prod
      args:
        PUBLIC_API_URL: ${PUBLIC_API_URL:-http://localhost}
        PUBLIC_WS_URL: ${PUBLIC_WS_URL:-ws://localhost}
    # Deploy
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
