version: "3.4"

# Services definition for local building & deployment

services:

  npm:
    # Build
    image: ${IMAGES_PREFIX:-app}-npm
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
      target: npm
    # Deploy
    volumes:
      - ../app:/app
