name: Check Astro site

on:
  # Runs on all pull requests
  pull_request:

# Sets permissions for the GITHUB_TOKEN
permissions:
  contents: read

jobs:
  # Check job
  check:
    name: Check Astro site

    # Runs on Ubuntu
    runs-on: ubuntu-latest

    # Maximum run time in minutes before the job is canceled
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Clean install
      run: npm clean-install

    - name: Check
      run: npm run check
