name: Check Astro site

on:
  # Runs on all pull requests
  pull_request:

# Sets permissions for the GITHUB_TOKEN
permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: ${{ github.event_name }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Check job
  check:
    name: Check Astro site
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Move to app directory
      run: cd ./app

    - name: Clean install
      run: npm clean-install

    - name: Check
      run: npm run check

  # Build job
  build:
    name: Build Astro site
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Move to app directory
      run: cd ./app

    - name: Clean install
      run: npm clean-install

    - name: Build
      run: npm run build
